# Generated by Django 6.0.5 on 2026-05-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedPDFJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(help_text='Identifier of the user or client (JWT sub, session ID, IP).', max_length=255)),
                ('filename', models.CharField(max_length=512)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes.')),
                ('pdf_version', models.CharField(blank=True, default='', max_length=10)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('operation_type', models.CharField(choices=[('metadata_analysis', 'Metadata Analysis'), ('text_extraction', 'Text Extraction'), ('page_render', 'Page Render'), ('full_analysis', 'Full Analysis')], default='full_analysis', max_length=30)),
                ('text_preview', models.TextField(blank=True, default='', help_text='First 500 characters of extracted text.')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Processed PDF Job',
                'verbose_name_plural': 'Processed PDF Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
