# Generated by Django 6.0.5 on 2026-05-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedpdfjob',
            name='operation_type',
            field=models.CharField(choices=[('metadata_analysis', 'Metadata Analysis'), ('text_extraction', 'Text Extraction'), ('page_render', 'Page Render'), ('full_analysis', 'Full Analysis'), ('merge', 'Merge PDFs'), ('split', 'Split PDF'), ('delete_pages', 'Delete Pages'), ('rotate_pages', 'Rotate Pages'), ('crop_pages', 'Crop Pages'), ('ocr', 'OCR'), ('export', 'Export')], default='full_analysis', max_length=30),
        ),
    ]
